---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upbound-aws-providerconfigs-rwx
  labels:
    rbac.crossplane.io/aggregate-to-provider: "true"
rules:
  - apiGroups: ["aws.upbound.io"]
    resources:
      - providerconfigs
      - providerconfigs/status
      - providerconfigusages
      - providerconfigusages/status
    verbs: ["get","list","watch","create","update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: direct-bind-provider-aws-s3-11170e658d51
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane:provider
subjects:
  - kind: ServiceAccount
    name: provider-aws-s3-11170e658d51 
    namespace: crossplane-system
