apiVersion: v1
kind: Secret
metadata:
  name: aws-creds-localstack
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
  access_key_id: test
  secret_access_key: test
