apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: demo-localstack-bucket
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-east-1
    forceDestroy: true
