apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObject
metadata:
  name: hello-txt
  namespace: crossplane-system
spec:
  forProvider:
    bucketRef:
      name: demo-localstack-bucket
    key: hello.txt
    content: "hello from crossplane via localstack"
    region: us-east-1
  providerConfigRef:
    name: default
